export default [
  // Edit
  {
    id: 'duplicate-pages',
    name: 'Duplicate pages',
    description: 'Create and move copies of pages',
    icon: 'duplicate.svg',
    cateogry: 'edit',
  },
  {
    id: 'delete-pages',
    name: 'Delete pages',
    description: 'Remove PDF pages',
    icon: 'remove.svg',
    cateogry: 'edit',
  },
  {
    id: 'rotate-pages',
    name: 'Rotate pages',
    description: 'Change the orientatio of PDF pages',
    icon: 'rotate.svg',
    cateogry: 'edit',
  },
  {
    id: 'order-pages',
    name: 'Order pages',
    description: 'Reorganize PDF pages',
    icon: 'order.svg',
    cateogry: 'edit',
  },
  {
    id: 'crop-pages',
    name: 'Crop pages',
    description: 'Trim PDF pages, adjust size and margins',
    icon: 'crop.svg',
    cateogry: 'edit',
  },
  {
    id: 'compress',
    name: 'Compress PDF',
    description: 'Reduce the size of PDF files',
    icon: 'compress.svg',
    cateogry: 'edit',
  },
  // Create
  // {
  //   id: 'extract-pages',
  //   name: 'Extract pages',
  //   description: 'Create a PDF from certain pages of an existing file',
  //   icon: 'extract.svg',
  //   cateogry: 'create',
  // },
  {
    id: 'split',
    name: 'Split/extract PDF pages',
    description: 'Split or extract pages from a PDF into new files',
    icon: 'split.svg',
    cateogry: 'create',
  },
  {
    id: 'merge',
    name: 'Merge PDFs',
    description: 'Merge multiple PDFs into one',
    icon: 'merge.svg',
    cateogry: 'create',
  },
  {
    id: 'images-to-pdf',
    name: 'Images to PDF',
    description: 'Turn JPG and PNG into a PDF with a custom layout',
    icon: 'images_to_pdf.svg',
    cateogry: 'create',
  },
  {
    id: 'pdf-to-images',
    name: 'PDF to images',
    description: 'Turn a PDF into JPG or PNG images',
    icon: 'pdf_to_images.svg',
    cateogry: 'create',
  },
  {
    id: 'word-to-pdf',
    name: 'Word to PDF',
    description: 'Turn a Microsoft Word document into a PDF',
    icon: 'word_to_pdf.svg',
    cateogry: 'create',
  },
  {
    id: 'ppt-to-pdf',
    name: 'PowerPoint to PDF',
    description: 'Turn a Microsoft PowerPoint presentation into a PDF',
    icon: 'ppt_to_pdf.svg',
    cateogry: 'create',
  },
  {
    id: 'excel-to-pdf',
    name: 'Excel to PDF',
    description: 'Turn a Microsoft Excel spreadsheet into a PDF',
    icon: 'excel_to_pdf.svg',
    cateogry: 'create',
  },
  // Secure
  {
    id: 'sign',
    name: 'Sign PDF',
    description: 'Add one or serveral signatures to a PDF',
    icon: 'sign.svg',
    cateogry: 'secure',
  },
  {
    id: 'add-password',
    name: 'Add PDF password',
    description: 'Secure a PDF with a password',
    icon: 'protect.svg',
    cateogry: 'secure',
  },
  {
    id: 'remove-password',
    name: 'Remove PDF password',
    description: 'Unlock a PDF by removing its password protection',
    icon: 'unlock.svg',
    cateogry: 'secure',
  },
  {
    id: 'watermark',
    name: 'Add watermark',
    description: 'Mark a PDF with a text or image watermark',
    icon: 'watermark.svg',
    cateogry: 'secure',
  },
];
