<template>
  <h1>Download</h1>

  <p class="endpoint">
    <code>
      <span class="get">GET</span> https://api.visualpdf.com/v1/download/{id}
    </code>
  </p>

  <p>
    Download a file generated by a pipeline processing.
  </p>
  <p>
    Only files generated by pipelines completed less than 1 hour ago are available for download.
  </p>

  <h2>Path parameters</h2>
  <vue-parameters-table>
    <!-- Files -->
    <tr>
      <td>id</td>
      <td>The id of the file to download, obtained in the result of a pipeline.</td>
      <td>String</td>
      <td>Yes</td>
    </tr>
  </vue-parameters-table>

  <h2>Example</h2>

  <h4>Request (NodeJS)</h4>
  <pre>
    <code class="language-javascript">
      const form = new FormData();
      // Adding files, tasks and options to the form...

      const pipelineResponse = await fetch(
        'https://api.visualpdf.com/v1/process',
        {
          method: 'POST',
          body: form,
          headers: { Authorization: `Bearer ${my_API_key}` },
        },
      );
      const pipelineResult = await pipelineResponse.json();

      // Downloading the first generated PDF
      const fileResponse = await fetch(
        pipelineResult.files[0].link,
        {
          method: 'GET',
          headers: { Authorization: `Bearer ${my_API_key}` },
        },
      );

      // Saving the file into a JavaScript File object
      const file = new File([await fileResponse.blob()], pipelineResult.files[0].name, { type: 'application/pdf' });
    </code>
  </pre>

  <h4>Response</h4>
  <p>
    The binary data of the file.
  </p>

  <h2>Errors</h2>
  <vue-parameters-table :cols="['HTTP code', 'Description']">
    <!-- Download format -->
    <tr>
      <td>400 - Bad Request</td>
      <td>The request was unacceptable, often due to missing or invalid file id.</td>
    </tr>
    <tr>
      <td>401 - Unauthorized</td>
      <td>No valid API key provided.</td>
    </tr>
    <tr>
      <td>404 - Not found</td>
      <td>The requested file doesn't exist.</td>
    </tr>
    <tr>
      <td>429 - Too Many Requests</td>
      <td>Too many requests hit the API too quickly.</td>
    </tr>
    <tr>
      <td>5xx - Server Errors</td>
      <td>Something went wrong on our end.</td>
    </tr>
  </vue-parameters-table>
</template>

<script lang="ts">
import { defineComponent } from 'vue';

import vueParametersTable from '../../components/docs/vue-parameters-table.vue';

export default defineComponent({
  name: 'DownloadDocsPost',
  components: {
    vueParametersTable,
  },
  data() {
    return {};
  },
});
</script>
